--
-- PostgreSQL database dump
--

\restrict RwpZoD6eSRakfbuY44dwEQNtwWnSV118jw7zwoejbE2oQtWbA9lnnbFV9TbELFA

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agreements; Type: TABLE; Schema: public; Owner: mieszkania_user
--

CREATE TABLE public.agreements (
    id integer NOT NULL,
    category character varying(255) NOT NULL,
    date_from date NOT NULL,
    date_to date,
    description character varying(255),
    monthly_net_value double precision NOT NULL,
    tax_operation boolean NOT NULL,
    vat_rate double precision NOT NULL,
    apartment_id integer NOT NULL,
    contractor_id integer NOT NULL
);


ALTER TABLE public.agreements OWNER TO mieszkania_user;

--
-- Name: agreements_id_seq; Type: SEQUENCE; Schema: public; Owner: mieszkania_user
--

ALTER TABLE public.agreements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agreements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apartments; Type: TABLE; Schema: public; Owner: mieszkania_user
--

CREATE TABLE public.apartments (
    id integer NOT NULL,
    apartment_number integer NOT NULL,
    area double precision NOT NULL,
    balcony_terrace_area double precision,
    city character varying(255) NOT NULL,
    garage_number character varying(255),
    house_number integer NOT NULL,
    number_of_rooms integer NOT NULL,
    parking_spot_number integer,
    postal_code character varying(6) NOT NULL,
    storage_unit boolean NOT NULL,
    street character varying(255) NOT NULL
);


ALTER TABLE public.apartments OWNER TO mieszkania_user;

--
-- Name: apartments_id_seq; Type: SEQUENCE; Schema: public; Owner: mieszkania_user
--

ALTER TABLE public.apartments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apartments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contractors; Type: TABLE; Schema: public; Owner: mieszkania_user
--

CREATE TABLE public.contractors (
    id integer NOT NULL,
    additional_info character varying(255),
    address character varying(255),
    contractor_type character varying(255),
    email character varying(255),
    name character varying(255) NOT NULL,
    pesel_or_nip character varying(255),
    phone character varying(255)
);


ALTER TABLE public.contractors OWNER TO mieszkania_user;

--
-- Name: contractors_id_seq; Type: SEQUENCE; Schema: public; Owner: mieszkania_user
--

ALTER TABLE public.contractors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contractors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses; Type: TABLE; Schema: public; Owner: mieszkania_user
--

CREATE TABLE public.expenses (
    apartment_id integer NOT NULL,
    amount double precision,
    category character varying(255),
    date date,
    description character varying(255)
);


ALTER TABLE public.expenses OWNER TO mieszkania_user;

--
-- Name: financial_entries; Type: TABLE; Schema: public; Owner: mieszkania_user
--

CREATE TABLE public.financial_entries (
    id integer NOT NULL,
    category character varying(255) NOT NULL,
    date date NOT NULL,
    description character varying(255),
    net_amount double precision NOT NULL,
    paid boolean NOT NULL,
    tax_operation boolean NOT NULL,
    vat_rate double precision NOT NULL,
    apartment_id integer
);


ALTER TABLE public.financial_entries OWNER TO mieszkania_user;

--
-- Name: financial_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: mieszkania_user
--

ALTER TABLE public.financial_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.financial_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meter_readings; Type: TABLE; Schema: public; Owner: mieszkania_user
--

CREATE TABLE public.meter_readings (
    apartment_id integer NOT NULL,
    cost double precision,
    date_from date,
    date_to date,
    reading double precision
);


ALTER TABLE public.meter_readings OWNER TO mieszkania_user;

--
-- Name: rent_payments; Type: TABLE; Schema: public; Owner: mieszkania_user
--

CREATE TABLE public.rent_payments (
    apartment_id integer NOT NULL,
    amount double precision,
    valid_from date,
    valid_to date
);


ALTER TABLE public.rent_payments OWNER TO mieszkania_user;

--
-- Name: users; Type: TABLE; Schema: public; Owner: mieszkania_user
--

CREATE TABLE public.users (
    id integer NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO mieszkania_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: mieszkania_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agreements agreements_pkey; Type: CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.agreements
    ADD CONSTRAINT agreements_pkey PRIMARY KEY (id);


--
-- Name: apartments apartments_pkey; Type: CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.apartments
    ADD CONSTRAINT apartments_pkey PRIMARY KEY (id);


--
-- Name: contractors contractors_pkey; Type: CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.contractors
    ADD CONSTRAINT contractors_pkey PRIMARY KEY (id);


--
-- Name: financial_entries financial_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.financial_entries
    ADD CONSTRAINT financial_entries_pkey PRIMARY KEY (id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: rent_payments fk6xsjn4duiu0qfnc2tm2p2fewp; Type: FK CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.rent_payments
    ADD CONSTRAINT fk6xsjn4duiu0qfnc2tm2p2fewp FOREIGN KEY (apartment_id) REFERENCES public.apartments(id);


--
-- Name: financial_entries fkbj2ff4205m6t1ugf0r914y16v; Type: FK CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.financial_entries
    ADD CONSTRAINT fkbj2ff4205m6t1ugf0r914y16v FOREIGN KEY (apartment_id) REFERENCES public.apartments(id);


--
-- Name: expenses fkbkwwpspbvv5ackr56944j4v66; Type: FK CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fkbkwwpspbvv5ackr56944j4v66 FOREIGN KEY (apartment_id) REFERENCES public.apartments(id);


--
-- Name: agreements fkj38b1jjm2kr8xral95o1s79dn; Type: FK CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.agreements
    ADD CONSTRAINT fkj38b1jjm2kr8xral95o1s79dn FOREIGN KEY (apartment_id) REFERENCES public.apartments(id);


--
-- Name: meter_readings fkj9c1fhcqf6yg2ul31sadlgy01; Type: FK CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.meter_readings
    ADD CONSTRAINT fkj9c1fhcqf6yg2ul31sadlgy01 FOREIGN KEY (apartment_id) REFERENCES public.apartments(id);


--
-- Name: agreements fkqnu93i7tm2x4uuftqsr4h0qwp; Type: FK CONSTRAINT; Schema: public; Owner: mieszkania_user
--

ALTER TABLE ONLY public.agreements
    ADD CONSTRAINT fkqnu93i7tm2x4uuftqsr4h0qwp FOREIGN KEY (contractor_id) REFERENCES public.contractors(id);


--
-- PostgreSQL database dump complete
--

\unrestrict RwpZoD6eSRakfbuY44dwEQNtwWnSV118jw7zwoejbE2oQtWbA9lnnbFV9TbELFA

